apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-master
  namespace: efk
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: master
