apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: efk
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200
